[package]
name = "rs_machine"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs_machine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module"] }
rand = "0.8.5"
